#36 - Add Event Page
latina-in-tech/latina-in-tech.github.io pull request #80
Opened 2023-12-22 17:47 UTC by zi0m0rgan

# 📚 Add Event Page
## What
1. Updated Metadata Front-Matter (added Speaker Section) as String[] of JSON objects (all fields in JSON are mandatory... if not present leave it to "", see example 20231129.mdx).
2. Added Interface ISpeaker in Event Model
3. Added component Event Card to show Event information (youtube link if url present, event registration link and with new Speaker Section)
4. Added Component AddToCalendar (extracted from EventWidget for reuse in EventCard)
5. Added Event Page that use param (search) for find an Event. If the event was found it will show the component (otherwise Alert component). Example http://localhost:3000/event?search=20231129

# 📝 To Do
a. Loading Spinner on EventPage (waiting correct information to be displayed)

2023-12-23 09:27 UTC, coluzziandrea requested changes
Thank you @zi0m0rgan  for your contribution! ❤️  I've added some comment, please do not close this PR, let's keep the history of it, it will be hard to understand if you keep re-open it 😢

2023-12-23 09:27 UTC, coluzziandrea commented on src/components/AddToCalendar.tsx
You did a very good job extracting this!

2023-12-23 09:27 UTC, coluzziandrea commented on src/pages/event/index.tsx
Creating an index page here would mean to access the event page by an URL similar to 'BASE_URL/event?search=EVENT_ID', it would be better to access the event page via 'BASE_URL/event/EVENT_ID' to match URI standard (check this [Stackoverflow answer](https://stackoverflow.com/a/31261026) for more details)

2023-12-23 09:27 UTC, coluzziandrea commented on src/pages/event/index.tsx
Also, there's already a WIP file in the repo: 'src/pages/events/[slug].tsx', this file is pretty much incomplete, but follows the uri above, you can simply copy your code into that file if you want (or yoink just the code that will get the event ID from the path)

2023-12-24 10:16 UTC, coluzziandrea approved these changes

2023-12-24 10:16 UTC, coluzziandrea commented
@Undermaken I'll fix leftovers from this PR in the near future :D

2023-12-24 10:16 UTC, merged

2023-12-24 10:23 UTC, Undermaken commented
> @Undermaken I'll fix leftovers from this PR in the near future :D 

I would like to contribute but I'm out due to a strong flu!

Thanks to both of you for this. I guess it's an interesting feature for our web site, especially to target specific events!

2023-12-24 12:13 UTC, coluzziandrea commented
yeah! That's a foundamental feature, don't worry I think I'll ber able to fix this before new year's eve 👍🏼